2.3
git-svn-id: file:///home/dev/bsdbuild/trunk@691 086a213a-9b02-0410-a1af-a7f5267bcc5c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -51,11 +51,23 @@ do
 	--sysconfdir=*)
 	    sysconfdir=$optarg
 	    ;;
+	--bindir=*)
+	    bindir=$optarg
+	    ;;
+	--libdir=*)
+	    libdir=$optarg
+	    ;;
 	--sharedir=*)
 	    sharedir=$optarg
 	    ;;
 	--localedir=*)
 	    localedir=$optarg
+	    ;;
+	--mandir=*)
+	    mandir=$optarg
+	    ;;
+	--infodir=*)
+	    infodir=$optarg
 	    ;;
 	--enable-*)
 	    option=`echo $arg | sed -e 's/--enable-//' -e 's/=.*//'`
@@ -97,6 +109,9 @@ do
 	--srcdir=*)
 	    srcdir=$optarg
 	    ;;
+	--testdir=*)
+	    testdir=$optarg
+	    ;;
 	*)
 	    echo "invalid argument: $arg"
 	    echo "try ./configure --help"
@@ -104,6 +119,17 @@ do
 	    ;;
 	esac
 done
+
+if [ -e "/bin/echo" ]; then
+    /bin/echo -n ""
+    if [ $? = 0 ]; then
+    	ECHO_N="/bin/echo -n"
+    else
+    	ECHO_N="echo -n"
+    fi
+else
+    ECHO_N="echo -n"
+fi
 
 if [ "${prefix}" != "" ]; then
     PREFIX="$prefix"
@@ -121,20 +147,37 @@ if [ "${srcdir}" != "" ]; then
 else
 	SRC=`pwd`
 fi
+
+if [ "${testdir}" != "" ]; then
+	echo "Configure tests will be executed in ${testdir}"
+	if [ ! -e "${testdir}" ]; then
+		echo "Creating ${testdir}"
+		mkdir ${testdir}
+	fi
+else
+	testdir="."
+fi
 if [ "${help}" = "yes" ]; then
 echo "Usage: ./configure [args]"
-echo "    --prefix                       Installation prefix [/usr/local]"
-echo "    --sysconfdir                   System-wide configuration prefix [/etc]"
-echo "    --sharedir                     Share prefix [$PREFIX/share]"
-echo "    --localedir                    Locale prefix [$PREFIX/share/locale]"
-echo "    --srcdir                       Source tree for concurrent build [.]"
-echo "    --help                         Display this message"
-echo "    --enable-nls                   Native Language Support [no]"
-echo "    --with-gettext                 Use gettext tools (msgmerge, ...) [check]"
-echo "    --with-libtool                 Specify path to libtool [check]"
-echo "    --with-manpages                Manual pages (-mdoc) [yes]"
-echo "    --with-docs                    Printable docs (-me/tbl/eqn/pic/refer) [no]"
-echo "    --enable-debug                 Include debugging code [no]"
+echo "    --prefix                  Installation prefix [/usr/local]"
+echo "    --sysconfdir              System-wide configuration prefix [/etc]"
+echo "    --bindir                  Executable directory [$PREFIX/bin]"
+echo "    --libdir                  Library directory [$PREFIX/lib]"
+echo "    --sharedir                Share directory [$PREFIX/share]"
+echo "    --localedir               Locale directory [$PREFIX/share/locale]"
+echo "    --mandir                  Manpage directory [$PREFIX/share/man]"
+echo "    --infodir                 Info directory [$PREFIX/share/info]"
+echo "    --srcdir                  Source tree for concurrent build [.]"
+echo "    --testdir                 Directory in which to execute tests [.]"
+echo "    --help                    Display this message"
+echo "    --enable-nls              Native Language Support [no]"
+echo "    --with-gettext            Use gettext tools (msgmerge, ...) [check]"
+echo "    --with-libtool            Specify path to libtool [bundled]"
+echo "    --with-cygwin             Add cygwin dependencies under cygwin [no]"
+echo "    --with-manpages           Manual pages (-mdoc) [yes]"
+echo "    --with-manlinks           Manual pages links for functions [no]"
+echo "    --with-docs               Printable docs (-me/tbl/eqn/pic/refer) [no]"
+echo "    --enable-debug            Include debugging code [no]"
 exit 1
 fi
 
@@ -163,14 +206,15 @@ for path in `echo $PATH | sed 's/:/ /g'`; do
 done
 if [ "${NROFF}" != "" ]; then
 	echo | ${NROFF} -Tmandoc >/dev/null
-	if [ $? == 0 ]; then
+	if [ "$?" = "0" ]; then
 		HAVE_MANDOC="yes"
 	fi
 fi
 if [ "${HAVE_MANDOC}" = "no" ]; then
 	if [ "${with_manpages}" = "yes" ]; then
 		echo "*"
-		echo "* --with-manpages requested, but nroff/mandoc not found."
+		echo "* --with-manpages was requested, but either the nroff(1)"
+		echo "* utility or the mdoc(7) macro package was not found."
 		echo "*"
 		exit 1
 	fi
@@ -182,6 +226,10 @@ else
 	if [ "${with_manpages}" = "no" ]; then
 		echo "NOMAN=yes" >> Makefile.config
 		echo "NOMANLINKS=yes" >> Makefile.config
+	else
+		if [ "${with_manlinks}" != "yes" ]; then
+			echo "NOMANLINKS=yes" >> Makefile.config
+		fi
 	fi
 fi
 
@@ -221,75 +269,93 @@ fi
 echo "ENABLE_NLS=${ENABLE_NLS}" >> Makefile.config
 echo "HAVE_GETTEXT=${HAVE_GETTEXT}" >> Makefile.config
 
-if [ "${with_libtool}" != "" ]; then
-	echo "LIBTOOL=${with_libtool}" >> Makefile.config
-else
-	ltool=""
-	for path in `echo $PATH | sed 's/:/ /g'`; do
-		if [ -x "${path}/libtool" ]; then
-			ltool=${path}/libtool
-		fi
-	done
-	if [ "${ltool}" != "" ]; then
-		echo "LIBTOOL=${ltool}" >> Makefile.config
-	else
-		echo "Warning: libtool not found on system, using bundled copy"
-		echo "LIBTOOL=\${TOP}/mk/libtool/libtool" >> Makefile.config
-	fi
-fi
+LIBTOOL_BUNDLED="yes"
+LIBTOOL=\${TOP}/mk/libtool/libtool
+echo "LIBTOOL=${LIBTOOL}" >> Makefile.config
 
 echo "PREFIX?=${PREFIX}" >> Makefile.config
 echo "#ifndef PREFIX" > config/prefix.h
 echo "#define PREFIX \"${PREFIX}\"" >> config/prefix.h
 echo "#endif /* PREFIX */" >> config/prefix.h
 
+if [ "${bindir}" != "" ]; then
+	BINDIR="${bindir}"
+else
+	BINDIR="${PREFIX}/bin"
+fi
+echo "BINDIR=${BINDIR}" >> Makefile.config
+echo "#ifndef BINDIR" > config/bindir.h
+echo "#define BINDIR \"${BINDIR}\"" >> config/bindir.h
+echo "#endif /* BINDIR */" >> config/bindir.h
+
+if [ "${libdir}" != "" ]; then
+	LIBDIR="${libdir}"
+else
+	LIBDIR="${PREFIX}/lib"
+fi
+echo "LIBDIR=${LIBDIR}" >> Makefile.config
+echo "#ifndef LIBDIR" > config/libdir.h
+echo "#define LIBDIR \"${LIBDIR}\"" >> config/libdir.h
+echo "#endif /* LIBDIR */" >> config/libdir.h
+
 if [ "${sharedir}" != "" ]; then
-	echo "SHAREDIR=${sharedir}" >> Makefile.config
-	echo "#ifndef SHAREDIR" > config/sharedir.h
-	echo "#define SHAREDIR \"${sharedir}\"" >> config/sharedir.h
-	echo "#endif /* SHAREDIR */" >> config/sharedir.h
 	SHAREDIR="${sharedir}"
 else
-	echo "SHAREDIR=\${PREFIX}/share" >> Makefile.config
-	echo "#ifndef SHAREDIR" > config/sharedir.h
-	echo "#define SHAREDIR \"${SHAREDIR}\"" >> config/sharedir.h
-	echo "#endif /* SHAREDIR */" >> config/sharedir.h
 	SHAREDIR="${PREFIX}/share"
 fi
+echo "SHAREDIR=${SHAREDIR}" >> Makefile.config
+echo "#ifndef SHAREDIR" > config/sharedir.h
+echo "#define SHAREDIR \"${SHAREDIR}\"" >> config/sharedir.h
+echo "#endif /* SHAREDIR */" >> config/sharedir.h
 
 if [ "${localedir}" != "" ]; then
 	LOCALEDIR="${localedir}"
-	echo "LOCALEDIR=${LOCALEDIR}" >> Makefile.config
-	echo "#ifndef LOCALEDIR" > config/localedir.h
-	echo "#define LOCALEDIR \"${LOCALEDIR}\"" >> config/localedir.h
-	echo "#endif /* LOCALEDIR */" >> config/localedir.h
 else
 	LOCALEDIR="${SHAREDIR}/locale"
-	echo "LOCALEDIR=\${SHAREDIR}/locale" >> Makefile.config
-	echo "#ifndef LOCALEDIR" > config/localedir.h
-	echo "#define LOCALEDIR \"${LOCALEDIR}\"" >> config/localedir.h
-	echo "#endif /* LOCALEDIR */" >> config/localedir.h
 fi
+echo "LOCALEDIR=${LOCALEDIR}" >> Makefile.config
+echo "#ifndef LOCALEDIR" > config/localedir.h
+echo "#define LOCALEDIR \"${LOCALEDIR}\"" >> config/localedir.h
+echo "#endif /* LOCALEDIR */" >> config/localedir.h
+
+if [ "${mandir}" != "" ]; then
+	MANDIR="${mandir}"
+else
+	MANDIR="${SHAREDIR}/man"
+fi
+echo "MANDIR=${MANDIR}" >> Makefile.config
+echo "#ifndef MANDIR" > config/mandir.h
+echo "#define MANDIR \"${MANDIR}\"" >> config/mandir.h
+echo "#endif /* MANDIR */" >> config/mandir.h
+
+if [ "${infodir}" != "" ]; then
+	INFODIR="${infodir}"
+else
+	INFODIR="${SHAREDIR}/info"
+fi
+echo "INFODIR=${INFODIR}" >> Makefile.config
+echo "#ifndef INFODIR" > config/infodir.h
+echo "#define INFODIR \"${INFODIR}\"" >> config/infodir.h
+echo "#endif /* INFODIR */" >> config/infodir.h
 
 if [ "${sysconfdir}" != "" ]; then
 	SYSCONFDIR="${sysconfdir}"
-	echo "SYSCONFDIR=${sysconfdir}" >> Makefile.config
-	echo "#ifndef SYSCONFDIR" > config/sysconfdir.h
-	echo "#define SYSCONFDIR \"${SYSCONFDIR}\"" >> config/sysconfdir.h
-	echo "#endif /* SYSCONFDIR */" >> config/sysconfdir.h
 else
 	SYSCONFDIR="${PREFIX}/etc"
-	echo "SYSCONFDIR=\${PREFIX}/etc" >> Makefile.config
-	echo "#ifndef SYSCONFDIR" > config/sysconfdir.h
-	echo "#define SYSCONFDIR \"${SYSCONFDIR}\"" >> config/sysconfdir.h
-	echo "#endif /* SYSCONFDIR */" >> config/sysconfdir.h
 fi
+echo "SYSCONFDIR=${SYSCONFDIR}" >> Makefile.config
+echo "#ifndef SYSCONFDIR" > config/sysconfdir.h
+echo "#define SYSCONFDIR \"${SYSCONFDIR}\"" >> config/sysconfdir.h
+echo "#endif /* SYSCONFDIR */" >> config/sysconfdir.h
 
 SHAREDIR="$PREFIX/share/bsdbuild"
-echo "SHAREDIR=$SHAREDIR" >> Makefile.config
-VERSION="2.2"
-echo "VERSION=$VERSION" >> Makefile.config
-RELEASE="Descent into Darkness"
-echo "RELEASE=$RELEASE" >> Makefile.config
+echo "SHAREDIR=$SHAREDIR" >>Makefile.config
+echo "mdefs[\"SHAREDIR\"] = \"$SHAREDIR\"" >>configure.lua
+VERSION="2.3"
+echo "VERSION=$VERSION" >>Makefile.config
+echo "mdefs[\"VERSION\"] = \"$VERSION\"" >>configure.lua
+RELEASE="Witching Hour"
+echo "RELEASE=$RELEASE" >>Makefile.config
+echo "mdefs[\"RELEASE\"] = \"$RELEASE\"" >>configure.lua
 echo "Don't forget to run \"make depend\"."
 echo "Don't forget to run \"make depend\"." >> config.log
